dependencies:
  - name: elasticsearch
    alias: catalogelasticsearch
    version: 1.4.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: catalogelasticsearch.enabled
  - name: inventory
    alias: inventory
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
    condition: inventory.enabled